sonar.projectKey=lamquangmanh_protobuf
sonar.projectName=protobuf

sonar.sources=src,proto
sonar.tests=test

# Exclude all generated code from analysis
sonar.exclusions=build/**,build/*,dist/**,dist/*,gen/**,gen/*,docs/**,docs/*,node_modules/**,node_modules/*,coverage/**,coverage/*
# Exclude generated code from duplication detection (copy-paste detection)
sonar.cpd.exclusions=build/**,build/*,dist/**,dist/*,gen/**,gen/*,**/*.pb.go,**/*.pb.gw.go,**/*.pb.ts,**/*.d.ts

sonar.typescript.tsconfigPath=tsconfig.json
