sonar.projectKey=lamquangmanh_protobuf
sonar.projectName=protobuf

sonar.sources=src,proto
sonar.tests=test

sonar.exclusions=build/**,dist/**,gen/**,docs/**,node_modules/**,coverage/**
sonar.cpd.exclusions=build/**,dist/**,gen/**,**/*.pb.go,**/*.d.ts

sonar.typescript.tsconfigPath=tsconfig.json
