syntax = "proto3";
package proto.base.v1;

option go_package = "go-api/pkg/api/basepb;basepb";

// import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

// define enum
enum FilterOperator {
  // this one is best practice to define <name>_UNSPECIFIED
  // read more: https://protobuf.dev/programming-guides/style/#enums
  FILTER_OPERATOR_UNSPECIFIED = 0;
  FILTER_OPERATOR_EQUAL = 1;
  FILTER_OPERATOR_NOT_EQUAL = 2;
  FILTER_OPERATOR_GREATER_THAN = 3;
  FILTER_OPERATOR_LESS_THAN = 4;
  FILTER_OPERATOR_GREATER_THAN_OR_EQUAL = 5;
  FILTER_OPERATOR_LESS_THAN_OR_EQUAL = 6;
  FILTER_OPERATOR_LIKE = 7;
  FILTER_OPERATOR_IN = 8;
  FILTER_OPERATOR_NOT_IN = 9;
}

enum SortOrder {
  SORT_ORDER_UNSPECIFIED = 0;
  SORT_ORDER_ASC = 1;
  SORT_ORDER_DESC = 2;
}

// define message
message PaginationRequest {
  int32 page = 1;
  int32 limit = 2;
}

message PaginationResponse {
  int32 page = 1;
  int32 limit = 2;
  int32 total_items = 3;
  int32 total_pages = 4;
  int32 item_count = 5;
}

message Sort {
  string field = 1; // created_at, updated_at
  SortOrder order = 2; // "ASC" or "DESC"
}

message Filter {
  string field = 1;
  FilterOperator operator = 2;
  optional string string_value = 3;
  optional string number_value = 4;
  optional string bool_value = 5;
  repeated string bool_values = 6;
  repeated string string_values = 7;
  repeated string number_values = 8;
  // google.protobuf.Value value = 9; // dynamic key-value object
}

message ErrorMessage {
  int32 code = 1;
  string message = 2;
  google.protobuf.Struct extra = 3; // dynamic key-value object
}

message CreateSuccess {
  bool success = 1;
  repeated ErrorMessage errors = 2;
}

message UpdateSuccess {
  bool success = 1;
  repeated ErrorMessage errors = 2;
}

message DeleteSuccess {
  bool success = 1;
  repeated ErrorMessage errors = 2;
}
