#!/usr/bin/env bash
set -euo pipefail

# Generate barrel exports for all proto modules in dist/proto/

DIST_DIR="./dist"
PROTO_DIR="${DIST_DIR}/proto"

# Ensure dist directory exists
mkdir -p "${DIST_DIR}"

# Create TypeScript declaration index
cat > "${DIST_DIR}/index.d.ts" << 'EOF'
// Re-export all generated protobuf types
// This file is auto-generated by generate-barrel-exports.sh

EOF

# Create JavaScript index
cat > "${DIST_DIR}/index.js" << 'EOF'
// Re-export all generated protobuf modules
// This file is auto-generated by generate-barrel-exports.sh

EOF

# Find all proto modules (scan recursively for v* subdirectories with .d.ts files)
if [ -d "${PROTO_DIR}" ]; then
  # Find all .d.ts files in dist/proto and extract their paths
  find "${PROTO_DIR}" -name "*.d.ts" -type f | sort | while read -r file; do
    # Get the relative path (e.g., "action/v1/action.d.ts")
    rel_path="${file#${PROTO_DIR}/}"
    
    # Extract module structure (e.g., "action/v1/action" from "action/v1/action.d.ts")
    # Remove .d.ts extension
    module_path="${rel_path%.d.ts}"
    
    # Add to TypeScript index
    {
      echo ""
      echo "// ${module_path}"
      echo "export * from './proto/${module_path}';"
    } >> "${DIST_DIR}/index.d.ts"
  done
  
  # Do the same for .js files
  find "${PROTO_DIR}" -name "*.js" -type f ! -name "*.js.map" | sort | while read -r file; do
    # Get the relative path
    rel_path="${file#${PROTO_DIR}/}"
    
    # Extract module structure
    # Remove .js extension
    module_path="${rel_path%.js}"
    
    # Add to JavaScript index
    {
      echo ""
      echo "// ${module_path}"
      echo "export * from './proto/${module_path}.js';"
    } >> "${DIST_DIR}/index.js"
  done
fi

echo "✓ Barrel exports generated successfully"
